[project]
name = "languagebench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.16.2",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "pycountry>=24.6.1",
]

[tool.uv]
dev-dependencies = [
    "aiolimiter>=1.1.0",
    "bert-score>=0.3.13",
    "datasets>=3.0.2",
    "elevenlabs>=1.53.0",
    "evaluate==0.4.0",
    "huggingface-hub>=0.29.1",
    "jiwer>=3.1.0",
    "joblib>=1.4.2",
    "langcodes>=3.5.0",
    "librosa>=0.10.2.post1",
    "openai>=1.52.2",
    "protobuf>=5.28.3",
    "pyglottolog>=3.14.0",
    "python-dotenv>=1.0.1",
    "sacrebleu>=2.4.3",
    "sentencepiece>=0.2.0",
    "soundfile>=0.13.1",
    "tiktoken>=0.8.0",
    "tqdm>=4.66.6",
    "transformers>=4.46.1",
]
