name: Nightly Evaluation Run

on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3am UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-evals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run evaluations
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          cd evals
          python main.py
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add results.json models.json languages.json
          git commit -m "Update evaluation results [skip ci]" || echo "No changes to commit"
          git push
          
      - name: Trigger Hugging Face upload
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: trigger-hf-upload
          token: ${{ secrets.GITHUB_TOKEN }} 